Repository GaloisInc/saw-script, pull requests merged in 2021-10, with the labels that each got.

#1475 Bump version number after 0.9 release
  saw-script.cabal
Labels: ready-to-merge

#1470 Coq inhabited errors
  cryptol-saw-core/saw/Cryptol.sawcore
  cryptol-saw-core/src/Verifier/SAW/Cryptol.hs
  saw-core-coq/coq/generated/CryptolToCoq/CryptolPrimitivesForSAWCore.v
  saw-core-coq/coq/generated/CryptolToCoq/SAWCorePrelude.v
  saw-core-coq/coq/handwritten/CryptolToCoq/CompM.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCorePrelude_proofs.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreVectorsAsCoqVectors.v
  saw-core-coq/src/Language/Coq/AST.hs
  saw-core-coq/src/Language/Coq/Pretty.hs
  saw-core-coq/src/Verifier/SAW/Translation/Coq.hs
  saw-core-coq/src/Verifier/SAW/Translation/Coq/SAWModule.hs
  saw-core-coq/src/Verifier/SAW/Translation/Coq/SpecialTreatment.hs
  saw-core-coq/src/Verifier/SAW/Translation/Coq/Term.hs
  saw-core/prelude/Prelude.sawcore
  saw-core/src/Verifier/SAW/Conversion.hs
  saw-core/src/Verifier/SAW/ExternalFormat.hs
  saw-core/src/Verifier/SAW/Grammar.y
  saw-core/src/Verifier/SAW/Lexer.x
  saw-core/src/Verifier/SAW/Module.hs
  saw-core/src/Verifier/SAW/OpenTerm.hs
  saw-core/src/Verifier/SAW/Recognizer.hs
  saw-core/src/Verifier/SAW/SCTypeCheck.hs
  saw-core/src/Verifier/SAW/SharedTerm.hs
  saw-core/src/Verifier/SAW/Simulator.hs
  saw-core/src/Verifier/SAW/Term/CtxTerm.hs
  saw-core/src/Verifier/SAW/Term/Functor.hs
  saw-core/src/Verifier/SAW/Term/Pretty.hs
  saw-core/src/Verifier/SAW/Typechecker.hs
  saw-core/src/Verifier/SAW/UntypedAST.hs
  src/SAWScript/Prover/Exporter.hs
Labels: ready-to-merge

#1467 [Heapster] Improve widening for changing offsets
  heapster-saw/examples/arrays.bc
  heapster-saw/examples/arrays.c
  heapster-saw/examples/arrays.saw
  heapster-saw/examples/arrays_proofs.v
  heapster-saw/examples/loops_proofs.v
  heapster-saw/src/Verifier/SAW/Heapster/Implication.hs
  heapster-saw/src/Verifier/SAW/Heapster/Permissions.hs
  heapster-saw/src/Verifier/SAW/Heapster/SAWTranslation.hs
  heapster-saw/src/Verifier/SAW/Heapster/TypedCrucible.hs
  heapster-saw/src/Verifier/SAW/Heapster/Widening.hs
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreBitvectors.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreVectorsAsCoqVectors.v
Labels: ready-to-merge, Heapster

#1478 [Heapster] Prove no_errors_mbox_randomize
  heapster-saw/examples/mbox.sawcore
  heapster-saw/examples/mbox_proofs.v
  saw-core-coq/coq/generated/CryptolToCoq/SAWCorePrelude.v
  saw-core-coq/src/Verifier/SAW/Translation/Coq/SpecialTreatment.hs
  saw-core/prelude/Prelude.sawcore
Labels: ready-to-merge, Heapster

#1477 CI cleanup
  .github/ci.sh
  .github/workflows/ci.yml
  saw-remote-api/scripts/test_docker.sh
Labels: ready-to-merge

#1486 upper bound on aeson version
  saw-remote-api/saw-remote-api.cabal
  saw-script.cabal
Labels: ready-to-merge

#1488 Added a new SAW command `heapster_init_env_for_files_debug`
  src/SAWScript/HeapsterBuiltins.hs
  src/SAWScript/Interpreter.hs
Labels: Heapster
