Repository GaloisInc/saw-script, pull requests merged in 2021-04, with the labels that each got.

#1162 refactor: use Tuple instead of Struct in saw-remote-api backend
  saw-remote-api/python/saw/llvm.py
  saw-remote-api/src/SAWServer.hs
  saw-remote-api/src/SAWServer/Data/SetupValue.hs
  saw-remote-api/src/SAWServer/LLVMCrucibleSetup.hs
Labels: ready-to-merge

#1111 Split testing, add cryptol-saw-core-tc-test via cabal-collect-bins action
  .github/ci.sh
  .github/workflows/build.yml
  cabal.GHC-8.10.3.config
  cabal.GHC-8.6.5.config
  cabal.GHC-8.8.4.config
  saw-remote-api/scripts/check_docs.sh
  saw-remote-api/scripts/run_rpc_tests.sh
Labels: build system

#1183 Add support for `prove` command and more provers to RPC API
  saw-remote-api/docs/SAW.rst
  saw-remote-api/docs/old-Saw.rst
  saw-remote-api/python/saw/__init__.py
  saw-remote-api/python/saw/commands.py
  saw-remote-api/python/saw/connection.py
  saw-remote-api/python/saw/proofscript.py
  saw-remote-api/python/tests/saw/test_provers.py
  saw-remote-api/src/SAWServer/ProofScript.hs
Labels: ready-to-merge, saw-remote-api

#1174 fix(rpc): tweak tests to avoid resource warnings
  saw-remote-api/python/saw/__init__.py
  saw-remote-api/python/saw/commands.py
  saw-remote-api/python/saw/connection.py
  saw-remote-api/python/tests/saw/test_alloc_aligned.py
  saw-remote-api/python/tests/saw/test_llvm_array_swap.py
  saw-remote-api/python/tests/saw/test_llvm_assert_null.py
  saw-remote-api/python/tests/saw/test_llvm_global.py
  saw-remote-api/python/tests/saw/test_llvm_pointer.py
  saw-remote-api/python/tests/saw/test_llvm_struct.py
  saw-remote-api/python/tests/saw/test_llvm_struct_type.py
  saw-remote-api/python/tests/saw/test_nested_struct.py
  saw-remote-api/python/tests/saw/test_nested_struct2.py
  saw-remote-api/python/tests/saw/test_points_to_at_type.py
  saw-remote-api/python/tests/saw/test_salsa20.py
  saw-remote-api/python/tests/saw/test_swap.py
  saw-remote-api/python/tests/saw_low_level/test_llvm_assume.py
  saw-remote-api/python/tests/saw_low_level/test_salsa20_low_level.py
  saw-remote-api/python/tests/saw_low_level/test_seven.py
  saw-remote-api/python/tests/saw_low_level/test_swap_low_level.py
  saw-remote-api/python/tests/saw_low_level/test_trivial.py
  saw-remote-api/scripts/run_rpc_tests.sh
Labels: ready-to-merge, saw-remote-api

#1108 Add support for ghost variables to remote API
  saw-remote-api/docs/SAW.rst
  saw-remote-api/python/saw/__init__.py
  saw-remote-api/python/saw/commands.py
  saw-remote-api/python/saw/connection.py
  saw-remote-api/python/saw/llvm.py
  saw-remote-api/python/tests/saw/test-files/ghost.bc
  saw-remote-api/python/tests/saw/test-files/ghost.c
  saw-remote-api/python/tests/saw/test-files/test.bc
  saw-remote-api/python/tests/saw/test-files/test.c
  saw-remote-api/python/tests/saw/test_ghost.py
  saw-remote-api/saw-remote-api.cabal
  saw-remote-api/saw-remote-api/Main.hs
  saw-remote-api/src/SAWServer.hs
  saw-remote-api/src/SAWServer/Data/Contract.hs
  saw-remote-api/src/SAWServer/Ghost.hs
  saw-remote-api/src/SAWServer/JVMCrucibleSetup.hs
  saw-remote-api/src/SAWServer/JVMVerify.hs
  saw-remote-api/src/SAWServer/LLVMCrucibleSetup.hs
  saw-remote-api/src/SAWServer/LLVMVerify.hs
Labels: ready-to-merge

#1154 remote-api: python client depend on PyPI cryptol package
  saw-remote-api/python/poetry.lock
  saw-remote-api/python/pyproject.toml
Labels: ready-to-merge

#1194 Handle x86 errors more gracefully
  src/SAWScript/Crucible/LLVM/X86.hs
  src/SAWScript/Value.hs
  src/SAWScript/X86.hs
Labels: ready-to-merge

#1193 Add commands for AIG and CNF generation via Verilog
  intTests/test_external_abc/test.saw
  intTests/test_external_abc/test.sh
  src/SAWScript/Builtins.hs
  src/SAWScript/Interpreter.hs
  src/SAWScript/Prover/Exporter.hs
Labels: ready-to-merge

#1198 Prepare documentation and such for v0.8 release
  CHANGES.md
  README.md
Labels: ready-to-merge

#1201 chore(rpc): update poetry.lock for python deps
  saw-remote-api/python/poetry.lock
Labels: ready-to-merge

#1203 Add release note about permutative rewrite rules
  CHANGES.md
Labels: ready-to-merge

#1208 updates from release 0.8 to master
  .github/ci.sh
  .github/workflows/ci.yml
  .github/workflows/docker.yml
  .github/workflows/nightly.yml
  CHANGES.md
  saw-remote-api/python/README.md
  saw-remote-api/python/pyproject.toml
  saw-remote-api/python/requirements.txt
  saw-remote-api/python/saw_client/__init__.py
  saw-remote-api/python/saw_client/commands.py
  saw-remote-api/python/saw_client/connection.py
  saw-remote-api/python/saw_client/dashboard.py
  saw-remote-api/python/saw_client/exceptions.py
  saw-remote-api/python/saw_client/llvm.py
  saw-remote-api/python/saw_client/proofscript.py
  saw-remote-api/python/saw_client/py.typed
  saw-remote-api/python/saw_client/utils.py
  saw-remote-api/python/setup.py
  saw-remote-api/python/tests/saw/test_alloc_aligned.py
  saw-remote-api/python/tests/saw/test_ghost.py
  saw-remote-api/python/tests/saw/test_llvm_array_swap.py
  saw-remote-api/python/tests/saw/test_llvm_assert_null.py
  saw-remote-api/python/tests/saw/test_llvm_global.py
  saw-remote-api/python/tests/saw/test_llvm_pointer.py
  saw-remote-api/python/tests/saw/test_llvm_struct.py
  saw-remote-api/python/tests/saw/test_llvm_struct_type.py
  saw-remote-api/python/tests/saw/test_nested_struct.py
  saw-remote-api/python/tests/saw/test_nested_struct2.py
  saw-remote-api/python/tests/saw/test_points_to_at_type.py
  saw-remote-api/python/tests/saw/test_provers.py
  saw-remote-api/python/tests/saw/test_salsa20.py
  saw-remote-api/python/tests/saw/test_swap.py
  saw-remote-api/python/tests/saw_low_level/test_llvm_assume.py
  saw-remote-api/python/tests/saw_low_level/test_salsa20_low_level.py
  saw-remote-api/python/tests/saw_low_level/test_seven.py
  saw-remote-api/python/tests/saw_low_level/test_swap_low_level.py
  saw-remote-api/python/tests/saw_low_level/test_trivial.py
  saw-remote-api/scripts/run_rpc_tests.sh
  saw-remote-api/scripts/test_docker.sh
  saw-script.cabal
Labels: ready-to-merge

#1214 saw/Dockerfile: Install libreadline-dev in last stage
  saw/Dockerfile
Labels: ready-to-merge

#1206 Use correct link for GitHub Actions README badge
  README.md
Labels: ready-to-merge

#1218 Improve errors when a non-function is applied to an argument
  saw-core/src/Verifier/SAW/SCTypeCheck.hs
Labels: ready-to-merge

#1204 Support building Heapster shapes from Rust type declarations
  src/SAWScript/HeapsterBuiltins.hs
  src/SAWScript/Interpreter.hs
Labels: enhancement

#1282 Use read_only=True in test_salsa20.py
  saw-remote-api/python/tests/saw/test_salsa20.py
Labels: ready-to-merge

#1281 Convert more uses of `String` to `Text`.
  cryptol-saw-core/src/Verifier/SAW/TypedTerm.hs
  saw-core-what4/src/Verifier/SAW/Simulator/What4/ReturnTrip.hs
  saw-core/src/Verifier/SAW/Constant.hs
  saw-core/src/Verifier/SAW/Rewriter.hs
  saw-core/src/Verifier/SAW/SharedTerm.hs
  saw-remote-api/src/SAWServer/JVMCrucibleSetup.hs
  saw-remote-api/src/SAWServer/LLVMCrucibleSetup.hs
  src/SAWScript/Builtins.hs
  src/SAWScript/Crucible/Common/Setup/Type.hs
  src/SAWScript/Crucible/JVM/Builtins.hs
  src/SAWScript/Crucible/LLVM/Builtins.hs
  src/SAWScript/Crucible/LLVM/ResolveSetupValue.hs
  src/SAWScript/Crucible/LLVM/Skeleton/Builtins.hs
  src/SAWScript/JavaExpr.hs
  src/SAWScript/Proof.hs
  src/SAWScript/Prover/MRSolver.hs
Labels: ready-to-merge
