Repository GaloisInc/saw-script, pull requests merged in 2021-02, with the labels that each got.

#1057 CI quickfix: Pin libBF==0.5.1 in cabal.GHC-8.6.5.config
  .github/workflows/build.yml
  .github/workflows/docker.yml
  .github/workflows/nightly.yml
  cabal.GHC-8.6.5.config
Labels: next-to-merge

#1025 Update GHC and package dependency version pinning
  .github/ci.sh
  .github/workflows/build.yml
  .github/workflows/nightly.yml
  README.md
  cabal.GHC-8.10.3.config
  cabal.GHC-8.6.5.config
  cabal.GHC-8.8.3.config
  cabal.GHC-8.8.4.config
Labels: ready-to-merge

#1065 Make all 'ready-to-merge PRs auto-update'
  .github/mergify.yml
Labels: ready-to-merge

#1070 Re-enable all disabled integration tests in .github/ci.sh.
  .github/ci.sh
Labels: ready-to-merge

#1071 determine more accurate verification-status
  src/SAWScript/VerificationSummary.hs
Labels: ready-to-merge

#1063 Remove find-java-rt-jar.sh, document how -b interacts with older JDKs
  .github/PropertiesTest.java
  .github/ci.sh
  doc/manual/manual.md
  intTests/runtests.sh
  intTests/support/find-java-rt-jar.sh
Labels: ready-to-merge

#1077 chore: fix docker image uploads, don't allow confusion over Dockerfiles
  .github/workflows/docker.yml
  .github/workflows/nightly.yml
  Dockerfile-remote-api
  saw-remote-api/Dockerfile
  saw/Dockerfile
Labels: ready-to-merge

#1087 Eschew -Weverything in favor of -Wall
  saw-remote-api/saw-remote-api.cabal
Labels: ready-to-merge

#1088 Add llvm_struct_type, llvm_packed_struct_type, and llvm_alias
  CHANGES.md
  doc/manual/manual.md
  examples/llvm/dotprod_struct.saw
  examples/llvm/iterative_average/test.saw
  examples/llvm/nested-full.saw
  examples/llvm/nested.saw
  examples/llvm/ptrcheck.saw
  examples/llvm/struct.saw
  examples/llvm/union/test.saw
  examples/partial-spec/partial-spec.saw
  examples/salsa20/djb/salsa20.saw
  intTests/test0028/test.saw
  intTests/test0031_unit_test/test.saw
  intTests/test0038_rust/test.saw
  intTests/test0051_compositional_extract_2/test.saw
  intTests/test0060/test.saw
  intTests/test0065_match_llvm_elem/test.saw
  intTests/test_llvm_sizeof/test.saw
  intTests/test_llvm_tuple/test.saw
  intTests/test_profiling/dotprod_struct.saw
  saw-remote-api/test-scripts/in-progress/HMAC/spec/HMAC.py
  saw-remote-api/test-scripts/in-progress/HMAC/spec/HMAC.saw
  saw-remote-api/test-scripts/llvm_struct.py
  src/SAWScript/Interpreter.hs
  src/SAWScript/LLVMBuiltins.hs
Labels: ready-to-merge

#1082 saw-remote-api: Support more llvm_points_to features
  saw-remote-api/docs/SAW.rst
  saw-remote-api/src/SAWServer.hs
  saw-remote-api/src/SAWServer/Data/Contract.hs
  saw-remote-api/src/SAWServer/JVMCrucibleSetup.hs
  saw-remote-api/src/SAWServer/LLVMCrucibleSetup.hs
  src/SAWScript/Crucible/LLVM/Builtins.hs
Labels: ready-to-merge

#1092 saw-remote-api: Synchronize Crucible setup values documentation
  saw-remote-api/docs/SAW.rst
Labels: documentation, ready-to-merge, saw-remote-api
