Repository GaloisInc/saw-script, pull requests merged in 2021-09, with the labels that each got.

#1443 Allow slashes in `write_aig_external` filenames
  intTests/test_external_abc/test.saw
  src/SAWScript/Prover/Exporter.hs
Labels: ready-to-merge

#1446 Don't depend on nightly job before Mergify runs
  .github/workflows/ci.yml
Labels: ready-to-merge

#1440 Heapster fix memcpy bug
  heapster-saw/src/Verifier/SAW/Heapster/Implication.hs
  heapster-saw/src/Verifier/SAW/Heapster/SAWTranslation.hs
Labels: ready-to-merge, Heapster

#1441 Heapster bugfix to update IRT wrt recent changes
  heapster-saw/examples/rust_data.bc
  heapster-saw/examples/rust_data.rs
  heapster-saw/examples/rust_data.saw
  heapster-saw/src/Verifier/SAW/Heapster/IRTTranslation.hs
Labels: ready-to-merge, Heapster

#1445 Fix Rust to Heapster type translation for functions with no return value
  heapster-saw/examples/xor_swap_rust.bc
  heapster-saw/examples/xor_swap_rust.saw
  heapster-saw/src/Verifier/SAW/Heapster/RustTypes.hs
Labels: ready-to-merge, Heapster

#1448 [Heapster] Changes pre 9/3/21 demo
  heapster-saw/README.md
  heapster-saw/examples/iter_linked_list.saw
  heapster-saw/examples/iter_linked_list_proofs.v
Labels: ready-to-merge, Heapster

#1449 Heapster disable debug output
  heapster-saw/src/Verifier/SAW/Heapster/Implication.hs
  heapster-saw/src/Verifier/SAW/Heapster/Permissions.hs
  heapster-saw/src/Verifier/SAW/Heapster/RustTypes.hs
  heapster-saw/src/Verifier/SAW/Heapster/SAWTranslation.hs
  heapster-saw/src/Verifier/SAW/Heapster/TypedCrucible.hs
  heapster-saw/src/Verifier/SAW/Heapster/Widening.hs
  src/SAWScript/HeapsterBuiltins.hs
  src/SAWScript/Interpreter.hs
  src/SAWScript/Value.hs
Labels: ready-to-merge, Heapster

#1450 Comment out the xor_swap_rust proof
  heapster-saw/examples/xor_swap_rust_proofs.v
Labels: Heapster

#1444 test: add poetry update to docker rpc test script
  saw-remote-api/python/poetry.lock
  saw-remote-api/scripts/test_docker.sh
Labels: ready-to-merge

#1398 Update SBV
  cabal.GHC-8.10.3.config
  cabal.GHC-8.10.4.config
  cabal.GHC-8.8.4.config
  saw-core-sbv/saw-core-sbv.cabal
  saw-core-sbv/src/Verifier/SAW/Simulator/SBV/SWord.hs
  saw-script.cabal
  src/SAWScript/Prover/SBV.hs
Labels: ready-to-merge

#1423 Coq prelude update
  cryptol-saw-core/saw/Cryptol.sawcore
  saw-core-coq/coq/generated/CryptolToCoq/CryptolPrelude.v
  saw-core-coq/coq/generated/CryptolToCoq/CryptolPrimitivesForSAWCore.v
  saw-core-coq/coq/generated/CryptolToCoq/SAWCorePrelude.v
  saw-core-coq/coq/handwritten/CryptolToCoq/CryptolPrimitivesForSAWCoreExtra.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreVectorsAsCoqVectors.v
  saw-core-coq/saw-core-coq.cabal
  saw-core-coq/src/Verifier/SAW/Translation/Coq/SpecialTreatment.hs
  saw-core-coq/src/Verifier/SAW/Translation/Coq/Term.hs
  saw-core/prelude/Prelude.sawcore
  saw-core/src/Verifier/SAW/Simulator/Prims.hs
  src/SAWScript/Prover/Exporter.hs
Labels: ready-to-merge

#1397 Add Java support to RPC API
  saw-remote-api/docs/SAW.rst
  saw-remote-api/python/saw_client/__init__.py
  saw-remote-api/python/saw_client/commands.py
  saw-remote-api/python/saw_client/connection.py
  saw-remote-api/python/saw_client/crucible.py
  saw-remote-api/python/saw_client/jvm.py
  saw-remote-api/python/saw_client/jvm_type.py
  saw-remote-api/python/saw_client/llvm.py
  saw-remote-api/python/saw_client/llvm_type.py
  saw-remote-api/python/tests/saw/test-files/Add.class
  saw-remote-api/python/tests/saw/test-files/Add.java
  saw-remote-api/python/tests/saw/test_basic_java.py
  saw-remote-api/saw-remote-api/Main.hs
  saw-remote-api/scripts/run_rpc_tests.sh
  saw-remote-api/src/SAWServer.hs
  saw-remote-api/src/SAWServer/JVMCrucibleSetup.hs
  saw-remote-api/src/SAWServer/JVMVerify.hs
  src/SAWScript/Options.hs
Labels: ready-to-merge

#1272 Avoid concatenating Text values in `termToPat`.
  saw-core/src/Verifier/SAW/Conversion.hs
  saw-core/src/Verifier/SAW/Term/Functor.hs
Labels: ready-to-merge

#1456 Heapster string literals
  heapster-saw/examples/rust_data.bc
  heapster-saw/examples/rust_data.rs
  heapster-saw/examples/rust_data.saw
  heapster-saw/heapster-saw.cabal
  heapster-saw/src/Verifier/SAW/Heapster/LLVMGlobalConst.hs
  heapster-saw/src/Verifier/SAW/Heapster/Permissions.hs
  heapster-saw/src/Verifier/SAW/Heapster/RustTypes.hs
  heapster-saw/src/Verifier/SAW/Heapster/SAWTranslation.hs
  heapster-saw/src/Verifier/SAW/Heapster/TypedCrucible.hs
  saw-core-coq/coq/generated/CryptolToCoq/CryptolPrimitivesForSAWCore.v
  saw-core-coq/coq/generated/CryptolToCoq/SAWCorePrelude.v
  saw-core/prelude/Prelude.sawcore
  saw-core/src/Verifier/SAW/OpenTerm.hs
  src/SAWScript/HeapsterBuiltins.hs
  src/SAWScript/Interpreter.hs
Labels: ready-to-merge, Heapster

#1459 Heapster array field implications
  heapster-saw/examples/arrays.saw
  heapster-saw/examples/clearbufs.sawcore
  heapster-saw/examples/iter_linked_list.sawcore
  heapster-saw/examples/mbox.saw
  heapster-saw/examples/mbox.sawcore
  heapster-saw/examples/mbox_proofs.v
  heapster-saw/examples/memcpy.saw
  heapster-saw/examples/rust_data.saw
  heapster-saw/examples/rust_lifetimes.saw
  heapster-saw/examples/string_set.sawcore
  heapster-saw/examples/xor_swap_proofs.v
  heapster-saw/src/Verifier/SAW/Heapster/IRTTranslation.hs
  heapster-saw/src/Verifier/SAW/Heapster/Implication.hs
  heapster-saw/src/Verifier/SAW/Heapster/Permissions.hs
  heapster-saw/src/Verifier/SAW/Heapster/RustTypes.hs
  heapster-saw/src/Verifier/SAW/Heapster/SAWTranslation.hs
  heapster-saw/src/Verifier/SAW/Heapster/TypeChecker.hs
  heapster-saw/src/Verifier/SAW/Heapster/TypedCrucible.hs
  heapster-saw/src/Verifier/SAW/Heapster/Widening.hs
  saw-core-coq/coq/generated/CryptolToCoq/SAWCorePrelude.v
  saw-core/prelude/Prelude.sawcore
Labels: Heapster

#1457 Get RPC Java proofs working under Docker
  saw-remote-api/Dockerfile
  saw-remote-api/scripts/test_docker.sh
Labels: ready-to-merge

#1458 Saw-core simulator speedups
  saw-core/src/Verifier/SAW/Simulator.hs
Labels: ready-to-merge

#1465 Allow REPL line continuation with \ on Windows
  saw/SAWScript/REPL/Haskeline.hs
Labels: ready-to-merge
