Repository GaloisInc/saw-script, pull requests merged in 2021-07, with the labels that each got.

#1330 Print sharing control
  saw-core/src/Verifier/SAW/Term/Pretty.hs
  src/SAWScript/Interpreter.hs
  src/SAWScript/Value.hs
Labels: ready-to-merge

#1365 Improvements to the Heapster Rust translation
  heapster-saw/examples/Makefile
  heapster-saw/examples/_CoqProject
  heapster-saw/examples/arrays.v
  heapster-saw/examples/rust_data.bc
  heapster-saw/examples/rust_data.rs
  heapster-saw/examples/rust_data.saw
  heapster-saw/examples/rust_data.v
  heapster-saw/src/Verifier/SAW/Heapster/CruUtil.hs
  heapster-saw/src/Verifier/SAW/Heapster/IRTTranslation.hs
  heapster-saw/src/Verifier/SAW/Heapster/Permissions.hs
  heapster-saw/src/Verifier/SAW/Heapster/RustTypes.hs
  heapster-saw/src/Verifier/SAW/Heapster/SAWTranslation.hs
  src/SAWScript/HeapsterBuiltins.hs
  src/SAWScript/Interpreter.hs
Labels: Heapster, ready-to-merge

#1371 change call site IDs to have an additional Int index
  heapster-saw/src/Verifier/SAW/Heapster/SAWTranslation.hs
  heapster-saw/src/Verifier/SAW/Heapster/TypedCrucible.hs
Labels: Heapster, ready-to-merge

#1373 Improved ptr permission implications
  heapster-saw/examples/Makefile
  heapster-saw/examples/_CoqProject
  heapster-saw/examples/clearbufs.bc
  heapster-saw/examples/clearbufs.c
  heapster-saw/examples/clearbufs.saw
  heapster-saw/examples/clearbufs.sawcore
  heapster-saw/examples/clearbufs.v
  heapster-saw/examples/clearbufs_proofs.v
  heapster-saw/src/Verifier/SAW/Heapster/Implication.hs
Labels: Heapster, ready-to-merge

#1374 Add mbox.c Heapster example
  heapster-saw/examples/Makefile
  heapster-saw/examples/_CoqProject
  heapster-saw/examples/mbox.bc
  heapster-saw/examples/mbox.c
  heapster-saw/examples/mbox.saw
  heapster-saw/examples/mbox.sawcore
  heapster-saw/examples/mbox.v
  heapster-saw/examples/mbox_proofs.v
  heapster-saw/examples/rust_data_proofs.v
  heapster-saw/examples/rust_lifetimes_proofs.v
Labels: ready-to-merge

#1369 Avoid breaking up bitvectors in Verilog output
  src/SAWScript/Prover/Exporter.hs
Labels: ready-to-merge

#1331 emacs-lisp code for running SAW in emacs
  inf-saw.el
Labels: ready-to-merge

#1366 Add a new experimental `term_theories` operation
  src/SAWScript/Builtins.hs
  src/SAWScript/Interpreter.hs
  src/SAWScript/Prover/What4.hs
Labels: ready-to-merge

#1329 add basic vim editor configuration for SAW
  vim-saw/doc/saw.txt
  vim-saw/ftdetect/saw.vim
  vim-saw/plugin/saw.vim
  vim-saw/syntax/saw.vim
Labels: ready-to-merge

#1378 Add test case for unfinished proofs
  intTests/test0069_unfinished/test.saw
  intTests/test0069_unfinished/test.sh
Labels: ready-to-merge

#1384 Implement a Heapster command to introduce new primitive functions
  src/SAWScript/HeapsterBuiltins.hs
  src/SAWScript/Interpreter.hs
Labels: Heapster, enhancement, ready-to-merge

#1394 Improve Heapster implication prover for opaque named shapes
  heapster-saw/examples/string_set.v
  heapster-saw/src/Verifier/SAW/Heapster/Implication.hs
  heapster-saw/src/Verifier/SAW/Heapster/Permissions.hs
Labels: Heapster

#1392 `saw-remote-api`: Remove uses of `undefined`
  saw-remote-api/src/SAWServer/SetOption.hs
Labels: ready-to-merge

#1370 Add support for memoized streams to the term model evaluator
  saw-core/src/Verifier/SAW/Simulator/TermModel.hs
Labels: ready-to-merge

#1399 Improve string names for locally-bound Heapster variables
  heapster-saw/src/Verifier/SAW/Heapster/Implication.hs
  heapster-saw/src/Verifier/SAW/Heapster/Permissions.hs
  heapster-saw/src/Verifier/SAW/Heapster/TypedCrucible.hs
Labels: Heapster
