Repository GaloisInc/saw-script, pull requests merged in 2022-02, with the labels that each got.

#1564 Pointer cast
  CHANGES.md
  crux-mir-comp/src/Mir/Compositional/Builder.hs
  crux-mir-comp/src/Mir/Compositional/MethodSpec.hs
  doc/manual/manual.md
  doc/manual/manual.pdf
  intTests/test_llvm_union/Makefile
  intTests/test_llvm_union/README
  intTests/test_llvm_union/test.bc
  intTests/test_llvm_union/test.c
  intTests/test_llvm_union/test.saw
  intTests/test_llvm_union/test.sh
  saw-remote-api/src/SAWServer.hs
  saw-remote-api/src/SAWServer/Data/Contract.hs
  saw-remote-api/src/SAWServer/Data/SetupValue.hs
  saw-remote-api/src/SAWServer/JVMCrucibleSetup.hs
  saw-remote-api/src/SAWServer/LLVMCrucibleSetup.hs
  src/SAWScript/Crucible/Common/MethodSpec.hs
  src/SAWScript/Crucible/Common/Setup/Type.hs
  src/SAWScript/Crucible/JVM/MethodSpecIR.hs
  src/SAWScript/Crucible/JVM/Override.hs
  src/SAWScript/Crucible/JVM/ResolveSetupValue.hs
  src/SAWScript/Crucible/LLVM/Builtins.hs
  src/SAWScript/Crucible/LLVM/MethodSpecIR.hs
  src/SAWScript/Crucible/LLVM/Override.hs
  src/SAWScript/Crucible/LLVM/ResolveSetupValue.hs
  src/SAWScript/Crucible/LLVM/X86.hs
  src/SAWScript/Interpreter.hs
Labels: ready-to-merge

#1574 Heapster: more rust bugfixes
  heapster-saw/examples/c_data.bc
  heapster-saw/examples/c_data.c
  heapster-saw/examples/c_data.saw
  heapster-saw/examples/memcpy.saw
  heapster-saw/examples/rust_data.bc
  heapster-saw/examples/rust_data.rs
  heapster-saw/examples/rust_data.saw
  heapster-saw/src/Verifier/SAW/Heapster/IRTTranslation.hs
  heapster-saw/src/Verifier/SAW/Heapster/Implication.hs
  heapster-saw/src/Verifier/SAW/Heapster/LLVMGlobalConst.hs
  heapster-saw/src/Verifier/SAW/Heapster/Parser.y
  heapster-saw/src/Verifier/SAW/Heapster/Permissions.hs
  heapster-saw/src/Verifier/SAW/Heapster/RustTypes.hs
  heapster-saw/src/Verifier/SAW/Heapster/SAWTranslation.hs
  heapster-saw/src/Verifier/SAW/Heapster/TypeChecker.hs
  heapster-saw/src/Verifier/SAW/Heapster/TypedCrucible.hs
  heapster-saw/src/Verifier/SAW/Heapster/UntypedAST.hs
  heapster-saw/src/Verifier/SAW/Heapster/Widening.hs
Labels: ready-to-merge

#1582 Dictionary translation changes for comparisons
  cryptol-saw-core/saw/Cryptol.sawcore
Labels: ready-to-merge

#1590 Added support for SAW core bitvector notations
  saw-core/src/Verifier/SAW/Grammar.y
  saw-core/src/Verifier/SAW/Lexer.x
  saw-core/src/Verifier/SAW/Term/Pretty.hs
  saw-core/src/Verifier/SAW/Typechecker.hs
  saw-core/src/Verifier/SAW/UntypedAST.hs
Labels: ready-to-merge, saw-core

#1589 Make `goal_eval_unint` handle functions with arguments of type `Nat`.
  saw-core-what4/src/Verifier/SAW/Simulator/What4.hs
Labels: ready-to-merge

#1596 [MRSolver] Split Mr. Solver work into multiple files
  saw-script.cabal
  src/SAWScript/Prover/MRSolver.hs
  src/SAWScript/Prover/MRSolver/Monad.hs
  src/SAWScript/Prover/MRSolver/SMT.hs
  src/SAWScript/Prover/MRSolver/Solver.hs
  src/SAWScript/Prover/MRSolver/Term.hs
Labels: ready-to-merge

#1598 [MRSolver] Refactor MRM monad, add infrastructure for widening co-inductive hypotheses
  src/SAWScript/Prover/MRSolver/Monad.hs
  src/SAWScript/Prover/MRSolver/SMT.hs
  src/SAWScript/Prover/MRSolver/Solver.hs
Labels: ready-to-merge, MRSolver
