Repository GaloisInc/saw-script, pull requests merged in 2022-12, with the labels that each got.

#1774 Adapt to `NuMatchingAny1` becoming a quantified constraint
  cabal.project
  heapster-saw/src/Verifier/SAW/Heapster/CruUtil.hs
  heapster-saw/src/Verifier/SAW/Heapster/Implication.hs
  heapster-saw/src/Verifier/SAW/Heapster/Permissions.hs
  heapster-saw/src/Verifier/SAW/Heapster/SAWTranslation.hs
  heapster-saw/src/Verifier/SAW/Heapster/TypedCrucible.hs
Labels: ready-to-merge

#1773 Fix two bugs in SAWCore's handing of infinite streams
  intTests/test1703/Makefile
  intTests/test1703/test.bc
  intTests/test1703/test.c
  intTests/test1703/test.cry
  intTests/test1703/test.saw
  intTests/test1703/test.sh
  intTests/test1768/test.cry
  intTests/test1768/test.saw
  intTests/test1768/test.sh
  saw-core-sbv/src/Verifier/SAW/Simulator/SBV.hs
  saw-core-what4/src/Verifier/SAW/Simulator/What4.hs
  saw-core/src/Verifier/SAW/Simulator/Prims.hs
Labels: ready-to-merge

#1776 `saw-core-coq`: Rudimentary `lia` support for bitvectors
  heapster-saw/examples/Makefile
  heapster-saw/examples/arrays_proofs.v
  heapster-saw/examples/linked_list_proofs.v
  saw-core-coq/.gitignore
  saw-core-coq/coq/_CoqProject
  saw-core-coq/coq/handwritten/CryptolToCoq/CompMExtra.v
  saw-core-coq/coq/handwritten/CryptolToCoq/CryptolPrimitivesForSAWCoreExtra.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreBitvectors.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreBitvectorsZifyU64.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCorePreludeExtra.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCorePrelude_proofs.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreVectorsAsCoqLists.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreVectorsAsCoqVectors.v
  saw-core-coq/src/Verifier/SAW/Translation/Coq/SpecialTreatment.hs
  saw-core-coq/src/Verifier/SAW/Translation/Coq/Term.hs
Labels: ready-to-merge, saw-core-coq

#1778 Use itree SpecM monad instead of CompM in Heapster
  .github/workflows/ci.yml
  heapster-saw/examples/_CoqProject
  heapster-saw/examples/arrays.bc
  heapster-saw/examples/c_data.saw
  heapster-saw/examples/global_var.sawcore
  heapster-saw/examples/io.bc
  heapster-saw/examples/io.c
  heapster-saw/examples/io.saw
  heapster-saw/examples/io.sawcore
  heapster-saw/examples/io_proofs.v
  heapster-saw/examples/linked_list.sawcore
  heapster-saw/examples/linked_list_proofs.v
  heapster-saw/examples/mbox.saw
  heapster-saw/examples/mbox.sawcore
  heapster-saw/examples/mbox_proofs.v
  heapster-saw/examples/memcpy.saw
  heapster-saw/examples/memcpy.sawcore
  heapster-saw/examples/rust_data.saw
  heapster-saw/examples/rust_lifetimes.saw
  heapster-saw/examples/sha512.saw
  heapster-saw/examples/string_set.sawcore
  heapster-saw/examples/xor_swap_rust.saw
  heapster-saw/src/Verifier/SAW/Heapster/HintExtract.hs
  heapster-saw/src/Verifier/SAW/Heapster/Implication.hs
  heapster-saw/src/Verifier/SAW/Heapster/LLVMGlobalConst.hs
  heapster-saw/src/Verifier/SAW/Heapster/Permissions.hs
  heapster-saw/src/Verifier/SAW/Heapster/SAWTranslation.hs
  heapster-saw/src/Verifier/SAW/Heapster/TypedCrucible.hs
  saw-core-coq/README.md
  saw-core-coq/coq/_CoqProject
  saw-core-coq/coq/handwritten/CryptolToCoq/CompM.v
  saw-core-coq/coq/handwritten/CryptolToCoq/Everything.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SpecMExtra.v
  saw-core-coq/src/Verifier/SAW/Translation/Coq/SpecialTreatment.hs
  saw-core-coq/src/Verifier/SAW/Translation/Coq/Term.hs
  saw-core/prelude/Prelude.sawcore
  saw-core/src/Verifier/SAW/Module.hs
  saw-core/src/Verifier/SAW/OpenTerm.hs
  src/SAWScript/HeapsterBuiltins.hs
  src/SAWScript/Interpreter.hs
Labels: ready-to-merge, Heapster

#1752 Minor Heapster docfixes
  heapster-saw/doc/Permissions.md
  src/SAWScript/Interpreter.hs
Labels: ready-to-merge, Heapster

#1775 Fall back to Z3 4.8.8 on AWSLC/BLST proofs
  .github/ci.sh
  .github/workflows/ci.yml
  s2nTests/scripts/awslc-entrypoint.sh
  s2nTests/scripts/blst-entrypoint.sh
  saw-remote-api/Dockerfile
  saw/Dockerfile
Labels: ready-to-merge, CI

#1769 Add interpreter command to print current working directory
  intTests/test_pwd/README.md
  intTests/test_pwd/test.sh
  saw/SAWScript/REPL/Command.hs
Labels: ready-to-merge

#1770 Reset directory on failed file interpretation
  intTests/test_directory_reset/README.md
  intTests/test_directory_reset/err/err.saw
  intTests/test_directory_reset/test.sh
  src/SAWScript/Interpreter.hs
  src/SAWScript/Value.hs
Labels: ready-to-merge
