Repository GaloisInc/saw-script, pull requests merged in 2023-10, with the labels that each got.

#1940 Add `llvm_ffi_setup` command
  CHANGES.md
  cryptol-saw-core/src/Verifier/SAW/CryptolEnv.hs
  doc/manual/manual.md
  doc/manual/manual.pdf
  intTests/IntegrationTest.hs
  intTests/test_ffi_verify/Makefile
  intTests/test_ffi_verify/README.md
  intTests/test_ffi_verify/test.bc
  intTests/test_ffi_verify/test.c
  intTests/test_ffi_verify/test.cry
  intTests/test_ffi_verify/test.saw
  intTests/test_ffi_verify/test.sh
  intTests/test_ffi_verify_salsa/Makefile
  intTests/test_ffi_verify_salsa/README.md
  intTests/test_ffi_verify_salsa/ecrypt-config.h
  intTests/test_ffi_verify_salsa/ecrypt-machine.h
  intTests/test_ffi_verify_salsa/ecrypt-portable.h
  intTests/test_ffi_verify_salsa/ecrypt-sync.h
  intTests/test_ffi_verify_salsa/salsa.bc
  intTests/test_ffi_verify_salsa/salsa.c
  intTests/test_ffi_verify_salsa/salsa.cry
  intTests/test_ffi_verify_salsa/salsa.saw
  intTests/test_ffi_verify_salsa/test.sh
  saw-core/src/Verifier/SAW/OpenTerm.hs
  saw-script.cabal
  src/SAWScript/Crucible/LLVM/FFI.hs
  src/SAWScript/Crucible/LLVM/Skeleton/Builtins.hs
  src/SAWScript/Interpreter.hs
  src/SAWScript/Value.hs
Labels: enhancement, ready-to-merge

#1952 MRSolver SpecM bugfixes
  cryptol-saw-core/src/Verifier/SAW/Cryptol/Monadify.hs
  heapster-saw/examples/Makefile
  heapster-saw/examples/SpecPrims.cry
  heapster-saw/examples/arrays.sawcore
  heapster-saw/examples/arrays_mr_solver.saw
  heapster-saw/examples/specPrims.saw
  src/SAWScript/Prover/MRSolver/Monad.hs
  src/SAWScript/Prover/MRSolver/Solver.hs
  src/SAWScript/Prover/MRSolver/Term.hs
Labels: MRSolver

#1941 `mir_static` and `mir_static_initializer`
  crucible-mir-comp/src/Mir/Compositional/Builder.hs
  crucible-mir-comp/src/Mir/Compositional/Override.hs
  doc/manual/manual.md
  doc/manual/manual.pdf
  intTests/test_mir_statics/Makefile
  intTests/test_mir_statics/test.linked-mir.json
  intTests/test_mir_statics/test.rs
  intTests/test_mir_statics/test.saw
  intTests/test_mir_statics/test.sh
  saw-remote-api/python/tests/saw/test-files/Makefile
  saw-remote-api/python/tests/saw/test-files/mir_statics.linked-mir.json
  saw-remote-api/python/tests/saw/test-files/mir_statics.rs
  saw-remote-api/python/tests/saw/test_mir_statics.py
  saw-remote-api/src/SAWServer/MIRCrucibleSetup.hs
  src/SAWScript/Crucible/MIR/Builtins.hs
  src/SAWScript/Crucible/MIR/MethodSpecIR.hs
  src/SAWScript/Crucible/MIR/Override.hs
  src/SAWScript/Crucible/MIR/ResolveSetupValue.hs
  src/SAWScript/Crucible/MIR/Setup/Value.hs
  src/SAWScript/Crucible/MIR/TypeShape.hs
  src/SAWScript/Interpreter.hs
Labels: ready-to-merge

#1962 CI: Build artifacts using GHC 9.2.7, exclude Windows GHC 8.10.7 job
  .github/ci.sh
  .github/workflows/ci.yml
  saw-remote-api/Dockerfile
  saw/Dockerfile
Labels: ready-to-merge
