Repository GaloisInc/saw-script, pull requests merged in 2023-08, with the labels that each got.

#1899 Manual: Document pitfalls of specifying code with bools
  doc/manual/manual.md
  doc/manual/manual.pdf
Labels: ready-to-merge

#1880 Yosys: Support compositional translation of sequential circuits
  doc/manual/manual.md
  doc/manual/manual.pdf
  saw-script.cabal
  src/SAWScript/Yosys.hs
  src/SAWScript/Yosys/Cell.hs
  src/SAWScript/Yosys/CompositionalTranslation.hs
  src/SAWScript/Yosys/IR.hs
  src/SAWScript/Yosys/Netgraph.hs
  src/SAWScript/Yosys/State.hs
  src/SAWScript/Yosys/Utils.hs
Labels: ready-to-merge, hardware

#1905 Toplevel rust translation
  heapster-saw/examples/rust_just_translation.saw
  heapster-saw/src/Verifier/SAW/Heapster/RustTypes.hs
  src/SAWScript/HeapsterBuiltins.hs
  src/SAWScript/Interpreter.hs
  src/SAWScript/Value.hs
Labels: ready-to-merge, Heapster

#1911 Add support for translating Cryptol constraint guards
  CHANGES.md
  cryptol-saw-core/saw/Cryptol.sawcore
  cryptol-saw-core/src/Verifier/SAW/Cryptol.hs
  intTests/test_constraint_guards/Test.cry
  intTests/test_constraint_guards/test.saw
  intTests/test_constraint_guards/test.sh
Labels: enhancement, ready-to-merge

#1915 Add `ogFromParam` to Cryptol URI when importing Cryptol names
  cryptol-saw-core/src/Verifier/SAW/Cryptol.hs
  intTests/test1892/A.cry
  intTests/test1892/F.cry
  intTests/test1892/I.cry
  intTests/test1892/J.cry
  intTests/test1892/M.cry
  intTests/test1892/test.saw
  intTests/test1892/test.sh
Labels: ready-to-merge

#1918 Add some autogenerated directories under `intTests/` to .gitignore
  .gitignore
  intTests/.gitignore
Labels: ready-to-merge

#1921 Add `LICENSE` file for `verif-viewer`
  verif-viewer/LICENSE
  verif-viewer/verif-viewer.cabal
Labels: ready-to-merge
