Repository GaloisInc/saw-script, pull requests merged in 2023-01, with the labels that each got.

#1792 Heapster: improved bitvector and automation support
  heapster-saw/doc/Permissions.md
  heapster-saw/examples/linked_list_proofs.v
  heapster-saw/examples/mbox_proofs.v
  heapster-saw/src/Verifier/SAW/Heapster/Implication.hs
  heapster-saw/src/Verifier/SAW/Heapster/Lexer.x
  heapster-saw/src/Verifier/SAW/Heapster/Parser.y
  heapster-saw/src/Verifier/SAW/Heapster/SAWTranslation.hs
  heapster-saw/src/Verifier/SAW/Heapster/Token.hs
  heapster-saw/src/Verifier/SAW/Heapster/TypeChecker.hs
  heapster-saw/src/Verifier/SAW/Heapster/UntypedAST.hs
  saw-core-coq/coq/handwritten/CryptolToCoq/SpecMExtra.v
  saw-core/prelude/Prelude.sawcore
Labels: ready-to-merge

#1795 Heapster: Avoid shift/reduce conflicts involving bitvector negation
  heapster-saw/src/Verifier/SAW/Heapster/Parser.y
Labels: ready-to-merge

#1790 Normalize Cryptol types on import
  cryptol-saw-core/src/Verifier/SAW/Cryptol.hs
  intTests/test_join_split/README.md
  intTests/test_join_split/join_split.saw
  intTests/test_join_split/test.sh
Labels: ready-to-merge

#1796 Heapster Widening and Implication Prover Improvements
  heapster-saw/src/Verifier/SAW/Heapster/Implication.hs
  heapster-saw/src/Verifier/SAW/Heapster/Permissions.hs
  heapster-saw/src/Verifier/SAW/Heapster/Widening.hs
Labels: ready-to-merge, Heapster

#1797 Revert #1790
  cryptol-saw-core/src/Verifier/SAW/Cryptol.hs
  intTests/test_join_split/README.md
  intTests/test_join_split/join_split.saw
  intTests/test_join_split/test.sh
Labels: ready-to-merge

#1798 Add UIP to the SAW core prelude
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v
  saw-core-coq/src/Verifier/SAW/Translation/Coq/SpecialTreatment.hs
  saw-core/prelude/Prelude.sawcore
Labels: ready-to-merge, saw-core

#1802 Don't define Rust-related `.bc` Makefile rules on CI
  heapster-saw/examples/Makefile
Labels: ready-to-merge

#1804 Heapster: Generate definitions for recursive function frames
  heapster-saw/src/Verifier/SAW/Heapster/SAWTranslation.hs
Labels: ready-to-merge, Heapster

#1806 Update monadification and MR solver to work with the SpecM monad
  .github/workflows/ci.yml
  cryptol-saw-core/saw/CryptolM.sawcore
  cryptol-saw-core/src/Verifier/SAW/Cryptol/Monadify.hs
  examples/mr_solver/SpecPrims.cry
  examples/mr_solver/monadify.saw
  examples/mr_solver/mr_solver_unit_tests.saw
  heapster-saw/examples/linked_list_mr_solver.saw
  saw-core-coq/README.md
  saw-core/prelude/Prelude.sawcore
  saw-core/src/Verifier/SAW/OpenTerm.hs
  src/SAWScript/Builtins.hs
  src/SAWScript/Interpreter.hs
  src/SAWScript/Prover/MRSolver.hs
  src/SAWScript/Prover/MRSolver/Monad.hs
  src/SAWScript/Prover/MRSolver/SMT.hs
  src/SAWScript/Prover/MRSolver/Solver.hs
  src/SAWScript/Prover/MRSolver/Term.hs
Labels: ready-to-merge, MRSolver
