Repository GaloisInc/saw-script, pull requests merged in 2023-09, with the labels that each got.

#1919 `SetupValue`: Use proper TTG-style extension fields
  crucible-mir-comp/src/Mir/Compositional/Builder.hs
  crucible-mir-comp/src/Mir/Compositional/Override.hs
  saw-script.cabal
  src/SAWScript/Crucible/Common/MethodSpec.hs
  src/SAWScript/Crucible/Common/Override.hs
  src/SAWScript/Crucible/Common/Setup/Value.hs
  src/SAWScript/Crucible/JVM/MethodSpecIR.hs
  src/SAWScript/Crucible/JVM/Override.hs
  src/SAWScript/Crucible/JVM/ResolveSetupValue.hs
  src/SAWScript/Crucible/JVM/Setup/Value.hs
  src/SAWScript/Crucible/LLVM/Builtins.hs
  src/SAWScript/Crucible/LLVM/MethodSpecIR.hs
  src/SAWScript/Crucible/LLVM/Override.hs
  src/SAWScript/Crucible/LLVM/ResolveSetupValue.hs
  src/SAWScript/Crucible/LLVM/Setup/Value.hs
  src/SAWScript/Crucible/MIR/MethodSpecIR.hs
  src/SAWScript/Crucible/MIR/Override.hs
  src/SAWScript/Crucible/MIR/ResolveSetupValue.hs
  src/SAWScript/Crucible/MIR/Setup/Value.hs
Labels: ready-to-merge

#1907 Add `mrsolver` tactic, remove old MRSolver interface
  cryptol-saw-core/src/Verifier/SAW/TypedTerm.hs
  examples/mr_solver/mr_solver_unit_tests.saw
  heapster-saw/examples/Makefile
  heapster-saw/examples/arrays_mr_solver.saw
  heapster-saw/examples/exp_explosion_mr_solver.saw
  heapster-saw/examples/linked_list_mr_solver.saw
  heapster-saw/examples/sha512_mr_solver.saw
  saw-script.cabal
  src/SAWScript/Builtins.hs
  src/SAWScript/Interpreter.hs
  src/SAWScript/Proof.hs
  src/SAWScript/Prover/MRSolver.hs
  src/SAWScript/Prover/MRSolver/Evidence.hs
  src/SAWScript/Prover/MRSolver/Monad.hs
  src/SAWScript/Prover/MRSolver/SMT.hs
  src/SAWScript/Prover/MRSolver/Solver.hs
  src/SAWScript/Prover/MRSolver/Term.hs
  src/SAWScript/Value.hs
Labels: MRSolver

#1928 Refactored saw-core-coq
  heapster-saw/examples/mbox_proofs.v
  heapster-saw/src/Verifier/SAW/Heapster/LLVMGlobalConst.hs
  saw-core-coq/src/Verifier/SAW/Translation/Coq.hs
  saw-core-coq/src/Verifier/SAW/Translation/Coq/CryptolModule.hs
  saw-core-coq/src/Verifier/SAW/Translation/Coq/SAWModule.hs
  saw-core-coq/src/Verifier/SAW/Translation/Coq/Term.hs
  saw-core/src/Verifier/SAW/Rewriter.hs
  saw-core/src/Verifier/SAW/SCTypeCheck.hs
  saw-core/src/Verifier/SAW/SharedTerm.hs
  saw-core/src/Verifier/SAW/Simulator.hs
  saw-core/src/Verifier/SAW/Term/Functor.hs
  saw-core/src/Verifier/SAW/Term/Pretty.hs
  saw-core/src/Verifier/SAW/Typechecker.hs
  saw-core/src/Verifier/SAW/TypedAST.hs
  saw-core/tests/src/Tests/Parser.hs
  src/SAWScript/Builtins.hs
  src/SAWScript/Proof.hs
Labels: ready-to-merge, saw-core-coq

#1925 `mir_array_value`
  crucible-mir-comp/src/Mir/Compositional/Builder.hs
  crucible-mir-comp/src/Mir/Compositional/Override.hs
  doc/manual/manual.md
  intTests/test_mir_verify_arrays/Makefile
  intTests/test_mir_verify_arrays/test.linked-mir.json
  intTests/test_mir_verify_arrays/test.rs
  intTests/test_mir_verify_arrays/test.saw
  intTests/test_mir_verify_arrays/test.sh
  saw-remote-api/CHANGELOG.md
  saw-remote-api/python/CHANGELOG.md
  saw-remote-api/python/saw_client/crucible.py
  saw-remote-api/python/tests/saw/test-files/mir_arrays.linked-mir.json
  saw-remote-api/python/tests/saw/test-files/mir_arrays.rs
  saw-remote-api/python/tests/saw/test_mir_arrays.py
  saw-remote-api/src/SAWServer.hs
  saw-remote-api/src/SAWServer/Data/SetupValue.hs
  saw-remote-api/src/SAWServer/JVMCrucibleSetup.hs
  saw-remote-api/src/SAWServer/LLVMCrucibleSetup.hs
  saw-remote-api/src/SAWServer/MIRCrucibleSetup.hs
  src/SAWScript/Crucible/MIR/Override.hs
  src/SAWScript/Crucible/MIR/ResolveSetupValue.hs
  src/SAWScript/Crucible/MIR/Setup/Value.hs
  src/SAWScript/Interpreter.hs
Labels: ready-to-merge

#1935 Handle `TError` in constrant guard translator
  cryptol-saw-core/src/Verifier/SAW/Cryptol.hs
  intTests/test_constraint_guards/Parameterized.cry
Labels: cryptol-saw-core

#1934 `mir_tuple_value`
  crucible-mir-comp/src/Mir/Compositional/Builder.hs
  crucible-mir-comp/src/Mir/Compositional/Override.hs
  doc/manual/manual.md
  intTests/test_mir_verify_tuples/Makefile
  intTests/test_mir_verify_tuples/test.linked-mir.json
  intTests/test_mir_verify_tuples/test.rs
  intTests/test_mir_verify_tuples/test.saw
  intTests/test_mir_verify_tuples/test.sh
  saw-remote-api/CHANGELOG.md
  saw-remote-api/python/CHANGELOG.md
  saw-remote-api/python/saw_client/crucible.py
  saw-remote-api/python/tests/saw/test-files/mir_tuples.linked-mir.json
  saw-remote-api/python/tests/saw/test-files/mir_tuples.rs
  saw-remote-api/python/tests/saw/test_mir_tuples.py
  saw-remote-api/src/SAWServer.hs
  saw-remote-api/src/SAWServer/Data/SetupValue.hs
  saw-remote-api/src/SAWServer/JVMCrucibleSetup.hs
  saw-remote-api/src/SAWServer/LLVMCrucibleSetup.hs
  saw-remote-api/src/SAWServer/MIRCrucibleSetup.hs
  src/SAWScript/Crucible/Common/MethodSpec.hs
  src/SAWScript/Crucible/Common/Setup/Value.hs
  src/SAWScript/Crucible/JVM/Override.hs
  src/SAWScript/Crucible/JVM/ResolveSetupValue.hs
  src/SAWScript/Crucible/JVM/Setup/Value.hs
  src/SAWScript/Crucible/LLVM/Override.hs
  src/SAWScript/Crucible/LLVM/ResolveSetupValue.hs
  src/SAWScript/Crucible/LLVM/Setup/Value.hs
  src/SAWScript/Crucible/MIR/Override.hs
  src/SAWScript/Crucible/MIR/ResolveSetupValue.hs
  src/SAWScript/Crucible/MIR/Setup/Value.hs
  src/SAWScript/Interpreter.hs
Labels: ready-to-merge

#1931 `mir_find_adt`, `mir_struct_value`, and friends
  crucible-mir-comp/src/Mir/Compositional/Builder.hs
  crucible-mir-comp/src/Mir/Compositional/Override.hs
  doc/manual/manual.md
  intTests/test_mir_verify_structs/Makefile
  intTests/test_mir_verify_structs/test.linked-mir.json
  intTests/test_mir_verify_structs/test.rs
  intTests/test_mir_verify_structs/test.saw
  intTests/test_mir_verify_structs/test.sh
  saw-remote-api/CHANGELOG.md
  saw-remote-api/docs/SAW.rst
  saw-remote-api/python/CHANGELOG.md
  saw-remote-api/python/saw_client/__init__.py
  saw-remote-api/python/saw_client/commands.py
  saw-remote-api/python/saw_client/connection.py
  saw-remote-api/python/saw_client/crucible.py
  saw-remote-api/python/saw_client/mir.py
  saw-remote-api/python/saw_client/mir_type.py
  saw-remote-api/python/tests/saw/test-files/mir_structs.linked-mir.json
  saw-remote-api/python/tests/saw/test-files/mir_structs.rs
  saw-remote-api/python/tests/saw/test_mir_structs.py
  saw-remote-api/saw-remote-api.cabal
  saw-remote-api/saw-remote-api/Main.hs
  saw-remote-api/src/SAWServer.hs
  saw-remote-api/src/SAWServer/Data/MIRType.hs
  saw-remote-api/src/SAWServer/Data/SetupValue.hs
  saw-remote-api/src/SAWServer/Exceptions.hs
  saw-remote-api/src/SAWServer/JVMCrucibleSetup.hs
  saw-remote-api/src/SAWServer/LLVMCrucibleSetup.hs
  saw-remote-api/src/SAWServer/MIRCrucibleSetup.hs
  saw-remote-api/src/SAWServer/MIRFindADT.hs
  saw-remote-api/src/SAWServer/MIRVerify.hs
  src/SAWScript/Crucible/Common/MethodSpec.hs
  src/SAWScript/Crucible/MIR/Builtins.hs
  src/SAWScript/Crucible/MIR/Override.hs
  src/SAWScript/Crucible/MIR/ResolveSetupValue.hs
  src/SAWScript/Crucible/MIR/Setup/Value.hs
  src/SAWScript/Interpreter.hs
  src/SAWScript/Value.hs
Labels: ready-to-merge

#1908 Use solver result caching in CI
  .github/workflows/ci.yml
  Setup.hs
  doc/manual/manual.md
  doc/manual/manual.pdf
  intTests/IntegrationTest.hs
  intTests/test_solver_cache/test.sh
  intTests/test_solver_cache/test_clean.saw
  s2nTests/docker-compose.yml
  s2nTests/scripts/awslc-entrypoint.sh
  s2nTests/scripts/blst-entrypoint.sh
  s2nTests/scripts/s2n-entrypoint.sh
  saw/Main.hs
  src/SAWScript/Interpreter.hs
  src/SAWScript/Options.hs
  src/SAWScript/SolverCache.hs
  src/SAWScript/SolverVersions.hs
Labels: CI

#1936 MIR: Achieve feature (+ documentation) parity between SAWScript and Python
  saw-remote-api/python/CHANGELOG.md
  saw-remote-api/python/saw_client/crucible.py
  saw-remote-api/python/saw_client/mir.py
  saw-remote-api/python/saw_client/mir_type.py
  saw-remote-api/python/tests/saw/test-files/mir_proclaim.linked-mir.json
  saw-remote-api/python/tests/saw/test-files/mir_proclaim.rs
  saw-remote-api/python/tests/saw/test_proclaim.py
  saw-remote-api/src/SAWServer/Data/MIRType.hs
Labels: saw-remote-api, ready-to-merge, crucible/mir

#1937 Add documentation for `prove_bisim`
  doc/manual/manual.md
  doc/manual/manual.pdf
  intTests/test_bisimulation/Comp.cry
  intTests/test_bisimulation/comp.saw
  intTests/test_bisimulation/test.sh
  src/SAWScript/Interpreter.hs
Labels: documentation, ready-to-merge

#1943 `w4_abc_{aiger,verilog}`: Handle variable-less properties correctly
  intTests/test1938/Makefile
  intTests/test1938/test.bc
  intTests/test1938/test.c
  intTests/test1938/test.saw
  intTests/test1938/test.sh
  src/SAWScript/Prover/ABC.hs
Labels: ready-to-merge

#1947 Fix `tupleOpenTerm'`
  saw-core/src/Verifier/SAW/OpenTerm.hs
Labels: ready-to-merge

#1949 iss-1932
  intTests/test_llvm_bound_check/Makefile
  intTests/test_llvm_bound_check/bound.bc
  intTests/test_llvm_bound_check/bound.c
  intTests/test_llvm_bound_check/bound.saw
  intTests/test_llvm_bound_check/test.sh
  src/SAWScript/Crucible/LLVM/ResolveSetupValue.hs
Labels: ready-to-merge

#1950 adding integration test for hash table
  intTests/test_hash_table/Makefile
  intTests/test_hash_table/ht_simplified.bc
  intTests/test_hash_table/ht_simplified.c
  intTests/test_hash_table/ht_simplified.cry
  intTests/test_hash_table/ht_simplified.saw
  intTests/test_hash_table/test.sh
Labels: ready-to-merge
