Repository GaloisInc/saw-script, pull requests merged in 2023-03, with the labels that each got.

#1821 Heapster ide info
  heapster-saw/heapster-saw.cabal
  heapster-saw/src/Verifier/SAW/Heapster/CruUtil.hs
  heapster-saw/src/Verifier/SAW/Heapster/GenMonad.hs
  heapster-saw/src/Verifier/SAW/Heapster/IDESupport.hs
  heapster-saw/src/Verifier/SAW/Heapster/Implication.hs
  heapster-saw/src/Verifier/SAW/Heapster/ImplicationError.hs
  heapster-saw/src/Verifier/SAW/Heapster/JSONExport.hs
  heapster-saw/src/Verifier/SAW/Heapster/NamedMb.hs
  heapster-saw/src/Verifier/SAW/Heapster/Permissions.hs
  heapster-saw/src/Verifier/SAW/Heapster/SAWTranslation.hs
  heapster-saw/src/Verifier/SAW/Heapster/TypedCrucible.hs
  src/SAWScript/HeapsterBuiltins.hs
  src/SAWScript/Interpreter.hs
  src/SAWScript/Value.hs
Labels: ready-to-merge, Heapster

#1835 CI: Use modern version of `action-docker-layer-caching`
  .github/workflows/ci.yml
Labels: ready-to-merge

#1817 Fix bugs in several Yosys cell implementations
  src/SAWScript/Yosys/Cell.hs
Labels: ready-to-merge

#1840 Expand help text for `llvm_compositional_extract` to cover arguments
  src/SAWScript/Interpreter.hs
Labels: documentation, ready-to-merge

#1844 Updates to Cryptol Monadification (+ add `qsort` to saw-core)
  cryptol-saw-core/saw/CryptolM.sawcore
  cryptol-saw-core/src/Verifier/SAW/Cryptol/Monadify.hs
  examples/mr_solver/monadify_module.saw
  heapster-saw/examples/sha512_mr_solver.saw
  saw-core-coq/coq/_CoqProject
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreVectorsAsCoqVectors.v
  saw-core-coq/coq/handwritten/CryptolToCoq/SpecMExtra.v
  saw-core-coq/saw/generate_scaffolding.saw
  saw-core-coq/src/Language/Coq/AST.hs
  saw-core-coq/src/Verifier/SAW/Translation/Coq/Term.hs
  saw-core/prelude/Prelude.sawcore
  saw-core/src/Verifier/SAW/Conversion.hs
  saw-core/src/Verifier/SAW/ExternalFormat.hs
  saw-core/src/Verifier/SAW/Grammar.y
  saw-core/src/Verifier/SAW/Lexer.x
  saw-core/src/Verifier/SAW/OpenTerm.hs
  saw-core/src/Verifier/SAW/Recognizer.hs
  saw-core/src/Verifier/SAW/SharedTerm.hs
  saw-core/src/Verifier/SAW/Term/CtxTerm.hs
  saw-core/src/Verifier/SAW/Term/Functor.hs
  saw-core/src/Verifier/SAW/Term/Pretty.hs
  saw-core/src/Verifier/SAW/Typechecker.hs
  saw-core/src/Verifier/SAW/TypedAST.hs
  saw-core/src/Verifier/SAW/UntypedAST.hs
  src/SAWScript/Interpreter.hs
  src/SAWScript/Prover/Exporter.hs
Labels: ready-to-merge, saw-core, MRSolver

#1830 Persistent structure-based term identifiers
  saw-core/src/Verifier/SAW/Name.hs
  saw-core/src/Verifier/SAW/Rewriter.hs
  saw-core/src/Verifier/SAW/SharedTerm.hs
  saw-core/src/Verifier/SAW/Term/Functor.hs
  src/SAWScript/HeapsterBuiltins.hs
Labels: ready-to-merge
