Repository GaloisInc/saw-script, pull requests merged in 2024-09, with the labels that each got.

#2110 Fix printing of arrays when they appear in counterexamples.
  CHANGES.md
  intTests/test2049/.gitignore
  intTests/test2049/Makefile
  intTests/test2049/Test.cry
  intTests/test2049/test.bc
  intTests/test2049/test.c
  intTests/test2049/test.log.1.good
  intTests/test2049/test.log.2.good
  intTests/test2049/test.saw
  intTests/test2049/test.sh
  saw-core-what4/saw-core-what4.cabal
  saw-core-what4/src/Verifier/SAW/Simulator/What4/FirstOrder.hs
  saw-core/saw-core.cabal
  saw-core/src/Verifier/SAW/FiniteValue.hs
Labels: error-messages, needs test, usability, tech-debt, error-handling

#2118 CI: Upgrade `{upload,download}-artifact` actions to v4
  .github/workflows/ci.yml
Labels: CI

#2121 Don't fail when What4 sends us a function-based array in a result.
  saw-core-what4/src/Verifier/SAW/Simulator/What4/FirstOrder.hs
  saw-core/src/Verifier/SAW/FiniteValue.hs
  saw-remote-api/src/SAWServer/ProofScript.hs
Labels: error-messages, usability, tech-debt, error-handling

#2116 Fix the way compute-coverage finds the hpc dir in dist-newstyle
  compute-coverage.sh
Labels: bug, CI
