Repository GaloisInc/saw-script, pull requests merged in 2024-02, with the labels that each got.

#2021 Rust tutorial improvements
  doc/rust-tutorial/rust-tutorial.md
Labels: documentation, ready-to-merge

#2024 Make the CI more robust w.r.t. the `test_comp_bisim` job
  .github/workflows/ci.yml
  intTests/IntegrationTest.hs
  intTests/disabled_tests_hpc.txt
  intTests/test_comp_bisim/cryptol/spec.cry
Labels: ready-to-merge, CI

#2030 Fix Heapster reachability permissions examples
  heapster-saw/examples/clearbufs.saw
  heapster-saw/examples/iter_linked_list.saw
  heapster-saw/examples/iter_linked_list.sawcore
  heapster-saw/examples/mbox.saw
  heapster-saw/examples/mbox.sawcore
  heapster-saw/src/Verifier/SAW/Heapster/SAWTranslation.hs
Labels: ready-to-merge, Heapster
