Repository GaloisInc/saw-script, pull requests merged in 2025-02, with the labels that each got.

#2210 CI: add more comments, pursuant to previous changes
  .github/workflows/ci.yml
Labels: type: enhancement, tooling: CI

#2211 Bump the entree-specs commit
  .github/workflows/ci.yml
  saw-core-coq/README.md
Labels: type: bug, PR: dependency bump, subsystem: saw-core-coq, tooling: CI, test assets

#2232 refactors and wibbles
  cryptol-saw-core/src/Verifier/SAW/Cryptol.hs
  cryptol-saw-core/src/Verifier/SAW/TypedTerm.hs
  heapster-saw/examples/mbox.sawcore
  saw-core/src/Verifier/SAW/SharedTerm.hs
  saw-core/src/Verifier/SAW/Simulator/TermModel.hs
  saw-core/src/Verifier/SAW/Simulator/Value.hs
  saw-core/src/Verifier/SAW/UntypedAST.hs
Labels: easy
