Repository GaloisInc/saw-script, pull requests merged in 2025-07, with the labels that each got.

#2457 Tullsen/cryptol saw core use no debruijn api
  cryptol-saw-core/src/CryptolSAWCore/Cryptol.hs
  cryptol-saw-core/src/CryptolSAWCore/CryptolEnv.hs
  intTests/test2049/test.log.1.good
  intTests/test2049/test.log.2.good
  intTests/test_llvm_errors/err001.log.good
Labels: tech debt

#2465 Fix `saw-core-{sbv,what4}` buglets involving `Vec`-related model values
  CHANGES.md
  intTests/test1094_2464/test.saw
  intTests/test1094_2464/test.sh
  saw-core-sbv/src/SAWCoreSBV/SBV.hs
  saw-core-what4/src/SAWCoreWhat4/What4.hs
Labels: subsystem: saw-core

#2496 Add `crux-mir-comp` Docker image
  .github/workflows/ci.yml
  crux-mir-comp/Dockerfile
Labels: tooling: CI
